# Generated by Django 4.1.2 on 2022-11-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbproductos',
            name='ProdNombre',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tbproductos',
            name='ProdName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
